name: Java_CI

on: [push]

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-22.04
    container: pipelinecomponents/hadolint:0.26.4
    steps:
      - uses: actions/checkout@v4
      - name: Run hadolint
        run: hadolint Dockerfile
  jsonlint:
    name: jsonLint
    runs-on: ubuntu-22.04
    container: pipelinecomponents/jsonlint:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run jsonlint
        run: find . -not -path './.git/*' -name '*.json' -type f -print0 | parallel --will-cite -k -0 -n1 jsonlint -q
  yamllint:
    name: yamllint
    runs-on: ubuntu-22.04
    container: pipelinecomponents/yamllint:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint -c config/yamllint/.yamllint .
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 16
    - name: Build with Maven
      run: mvn -B package --file pom.xml
